### ISSUE TITLE
enhancement for saved settings json

### ISSUE THREAD

**Issue by seanpowell75** [Nuix/Batch-Load-Report#1]
Not a bug exactly, but I noticed that when you save the current settings in a json file, you need to browse and load the file the next time you run it.  For my usage, I'd prefer to have the settings last used load automatically next time the script is run.  I've seen this done before on one of your other scripts (I think), so I'd be keen to see this implemented in a future version.

**Comment by seanpowell75** [comment]
actually, can disregard, I found the required code line and added it in at line 30:
dialog.enableStickySettings(File.join(File.dirname(__FILE__),"RecentSettings.json"))

(also added another validation to check that report_csv was populated, as I received a script error the first time I tried to run it without populating this first)

thanks

**Comment by JuicyDragon** [comment]
You beat me to the answer of your own question 😄
